### ISSUE TITLE
CRAN plans / help wanted?

### ISSUE THREAD

**Issue by MilesMcBain** [obrl-soil/h3jsr#1]
Are there any significant blockers stopping this from going to CRAN?

We're using this a lot at work, I'd be happy to pitch in to get it there.

**Comment by obrl-soil** [comment]
Oh! Nothing major afaik, but I was thinking an rcpp-powered version that hooks into the original H3 lib would be more efficient. I saw a couple of people who looked like they were working on that (https://github.com/crazycapivara/h3-r and https://github.com/scottmmjackson/h3r) so I figured this would become redundant quickly, but neither project seems to have progressed much.

**Comment by MilesMcBain** [comment]
Yeah AFAIK there were difficulties with building the C version on Windows and that has been a blocker for those projects. I think that is just getting better now.

I see the JS wrapper as valuable in its own right, even if a fully blown C one eventually comes along.

**Comment by obrl-soil** [comment]
Hmm ok, well I guess I could give it a shot. I've just updated the core lib to the current version, so the only blocker now is that the vignette won't build on linux for Mystery Reasons. I'll start an issue for that and would appreciate any insights :)

**Comment by rafapereirabr** [comment]
Hi all. Any update on getting this package on CRAN?

**Comment by obrl-soil** [comment]
Life stuff's been in the way, mostly, but funnily enough I was thinking about it the other day. Might do some maintenance tonight and review it against CRAN policies.

**Comment by rafapereirabr** [comment]
hi @obrl-soil .  This is a really great package and it would be a great contribution to the R spatial community. thanks a lot, and take your time !

**Comment by obrl-soil** [comment]
update: Still intending to submit this one, but there's a major API revamp underway in the core library so I'm just going to wait until that propagates out through the transpile.
