### ISSUE TITLE
Bug in freeing geo polygon memory

### ISSUE THREAD

**Issue by Joaoeduardo81** [obrl-soil/h3jsr#9]
As of bug[ #103 (https://github.com/uber/h3-js/issues/103) in H3-js 
Inconsistent results from polyfill after calling polyfill with complex polygon crossing antimeridian

**Comment by nrabinowitz** [comment]
Should potentially be fixed with a simple upgrade to `h3-js@3.7.1`

**Comment by obrl-soil** [comment]
Updated to 3.7.1 as of 1aa1fc7 - any issues, let me know
